# Root of the zsh configuration
#
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
source $XDG_CONFIG_HOME/zsh/init.sh

export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/imagemagick-full/bin:$PATH"
